# Base configs
baseurl: "https://mattwind.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Matt Wind"
subtitle: "Just another photographer."
author: "Matt Wind"
header:
 title: "Photography"
 subtitle: "by Matt Wind"
footer:
 name: "Hey there, my name is Matt"
 bio: "I am a System Admin and a tech aficionado from California." 
 github: "Want a website like this? Just <a href=\"https://github.com/ramswaroop/photography\">fork it</a> from ramswaroop on github ;)"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/"
  twitter: "https://www.twitter.com/mattwind"
  instagram: "https://www.instagram.com/"
  dribbble: "https://dribbble.com/"
  linkedin: "https://in.linkedin.com/in/mattwind"
  github: "https://github.com/mattwind"
